// 1,666
exports.getAKData = () => {
    let ak_47 = [
        {object: "ak-47", assetName: "background", propertyName: "color_1", propertyAmount: 101},
        {object: "ak-47", assetName: "background", propertyName: "color_2", propertyAmount: 138},
        {object: "ak-47", assetName: "background", propertyName: "color_3", propertyAmount: 178},
        {object: "ak-47", assetName: "background", propertyName: "color_4", propertyAmount: 191},
        {object: "ak-47", assetName: "background", propertyName: "color_5", propertyAmount: 225},
        {object: "ak-47", assetName: "background", propertyName: "landscape_1", propertyAmount: 147},
        {object: "ak-47", assetName: "background", propertyName: "landscape_2", propertyAmount: 242},
        {object: "ak-47", assetName: "background", propertyName: "landscape_3", propertyAmount: 83},
        {object: "ak-47", assetName: "background", propertyName: "landscape_4", propertyAmount: 177},
        {object: "ak-47", assetName: "background", propertyName: "landscape_5", propertyAmount: 17},
        {object: "ak-47", assetName: "background", propertyName: "unique_1", propertyAmount: 4},
        {object: "ak-47", assetName: "background", propertyName: "unique_2", propertyAmount: 18},
        {object: "ak-47", assetName: "background", propertyName: "unique_3", propertyAmount: 30},
        {object: "ak-47", assetName: "background", propertyName: "unique_4", propertyAmount: 45},
        {object: "ak-47", assetName: "background", propertyName: "unique_5", propertyAmount: 70},
    
        {object: "ak-47", assetName: "optics", propertyName: "iron sights", propertyAmount: 1024},
        {object: "ak-47", assetName: "optics", propertyName: "red dot", propertyAmount: 326},
        {object: "ak-47", assetName: "optics", propertyName: "4x scope", propertyAmount: 135},
        {object: "ak-47", assetName: "optics", propertyName: "thermal", propertyAmount: 18},
        {object: "ak-47", assetName: "optics", propertyName: "8x scope", propertyAmount: 90},
        {object: "ak-47", assetName: "optics", propertyName: "acog", propertyAmount: 41},
        {object: "ak-47", assetName: "optics", propertyName: "16x scope", propertyAmount: 27},
        {object: "ak-47", assetName: "optics", propertyName: "night vision", propertyAmount: 5},
    
        {object: "ak-47", assetName: "finish", propertyName: "all black", propertyAmount: 163},
        {object: "ak-47", assetName: "finish", propertyName: "skin_1 (camo 1)", propertyAmount: 105},
        {object: "ak-47", assetName: "finish", propertyName: "skin_2 (camo 2)", propertyAmount: 102},
        {object: "ak-47", assetName: "finish", propertyName: "skin_3 (camo 3)", propertyAmount: 117},
        {object: "ak-47", assetName: "finish", propertyName: "skin_4", propertyAmount: 99},
        {object: "ak-47", assetName: "finish", propertyName: "skin_5", propertyAmount: 97},
        {object: "ak-47", assetName: "finish", propertyName: "skin_6", propertyAmount: 88},
        {object: "ak-47", assetName: "finish", propertyName: "cardano", propertyAmount: 87},
        {object: "ak-47", assetName: "finish", propertyName: "skin_7", propertyAmount: 83},
        {object: "ak-47", assetName: "finish", propertyName: "urban", propertyAmount: 80},
        {object: "ak-47", assetName: "finish", propertyName: "skin_8", propertyAmount: 76},
        {object: "ak-47", assetName: "finish", propertyName: "dust", propertyAmount: 70},
        {object: "ak-47", assetName: "finish", propertyName: "black & gold", propertyAmount: 50},
        {object: "ak-47", assetName: "finish", propertyName: "marijuana", propertyAmount: 66},
        {object: "ak-47", assetName: "finish", propertyName: "jungle", propertyAmount: 61},
        {object: "ak-47", assetName: "finish", propertyName: "ice", propertyAmount: 57},
        {object: "ak-47", assetName: "finish", propertyName: "burn", propertyAmount: 53},
        {object: "ak-47", assetName: "finish", propertyName: "ghillie wrap", propertyAmount: 47},
        {object: "ak-47", assetName: "finish", propertyName: "reggae", propertyAmount: 43},
        {object: "ak-47", assetName: "finish", propertyName: "solid white", propertyAmount: 40},
        {object: "ak-47", assetName: "finish", propertyName: "green money bill", propertyAmount: 36},
        {object: "ak-47", assetName: "finish", propertyName: "psychedelic", propertyAmount: 30},
        {object: "ak-47", assetName: "finish", propertyName: "chrome", propertyAmount: 13},
        {object: "ak-47", assetName: "finish", propertyName: "gold", propertyAmount: 3},
    
        {object: "ak-47", assetName: "magazine", propertyName: "standard", propertyAmount: 1410},
        {object: "ak-47", assetName: "magazine", propertyName: "extended", propertyAmount: 169},
        {object: "ak-47", assetName: "magazine", propertyName: "drum", propertyAmount: 87},
    
        {object: "ak-47", assetName: "stock", propertyName: "factory", propertyAmount: 1332},
        {object: "ak-47", assetName: "stock", propertyName: "skeleton", propertyAmount: 162},
        {object: "ak-47", assetName: "stock", propertyName: "tactical_2", propertyAmount: 98},
        {object: "ak-47", assetName: "stock", propertyName: "tactical_3", propertyAmount: 74},
    
        {object: "ak-47", assetName: "muzzle", propertyName: "break", propertyAmount: 732},
        {object: "ak-47", assetName: "muzzle", propertyName: "silence", propertyAmount: 665},
        {object: "ak-47", assetName: "muzzle", propertyName: "flash", propertyAmount: 202},
        {object: "ak-47", assetName: "muzzle", propertyName: "compensator", propertyAmount: 67},
    
        {object: "ak-47", assetName: "attachment_1", propertyName: "none", propertyAmount: 864},
        {object: "ak-47", assetName: "attachment_1", propertyName: "laser", propertyAmount: 750},
        {object: "ak-47", assetName: "attachment_1", propertyName: "flashlight", propertyAmount: 52},
    
        {object: "ak-47", assetName: "attachment_2", propertyName: "none", propertyAmount: 1417},
        {object: "ak-47", assetName: "attachment_2", propertyName: "bayonette", propertyAmount: 146},
        {object: "ak-47", assetName: "attachment_2", propertyName: "underbarrel shotgun", propertyAmount: 69},
        {object: "ak-47", assetName: "attachment_2", propertyName: "grenade launcher", propertyAmount: 34},
    
        {object: "ak-47", assetName: "attachment_3", propertyName: "none", propertyAmount: 1363},
        {object: "ak-47", assetName: "attachment_3", propertyName: "vertical grip", propertyAmount: 178},
        {object: "ak-47", assetName: "attachment_3", propertyName: "foregrip", propertyAmount: 125},
    
        {object: "ak-47", assetName: "bonus", propertyName: "none", propertyAmount: 853},
        {object: "ak-47", assetName: "bonus", propertyName: "flashlight", propertyAmount: 123},
        {object: "ak-47", assetName: "bonus", propertyName: "ammo can", propertyAmount: 122},
        {object: "ak-47", assetName: "bonus", propertyName: "knife", propertyAmount: 110},
        {object: "ak-47", assetName: "bonus", propertyName: "radio", propertyAmount: 80},
        {object: "ak-47", assetName: "bonus", propertyName: "backpack", propertyAmount: 75},
        {object: "ak-47", assetName: "bonus", propertyName: "binoculars", propertyAmount: 67},
        {object: "ak-47", assetName: "bonus", propertyName: "med kit", propertyAmount: 66},
        {object: "ak-47", assetName: "bonus", propertyName: "flare", propertyAmount: 51},
        {object: "ak-47", assetName: "bonus", propertyName: "multi tool", propertyAmount: 45},
        {object: "ak-47", assetName: "bonus", propertyName: "pills", propertyAmount: 44},
        {object: "ak-47", assetName: "bonus", propertyName: "rocket launcher", propertyAmount: 13},
        {object: "ak-47", assetName: "bonus", propertyName: "money bag", propertyAmount: 11},
        {object: "ak-47", assetName: "bonus", propertyName: "atv", propertyAmount: 5},
        {object: "ak-47", assetName: "bonus", propertyName: "truck", propertyAmount: 1},
    ];

    return ak_47;
}

// ----------------------------------------------------------------------------

// 2,317
exports.getAUGData = () => {
    let aug = [
        {assetName: "background", propertyName: "color_1", propertyAmount: 0},
        {assetName: "background", propertyName: "color_2", propertyAmount: 0},
        {assetName: "background", propertyName: "color_3", propertyAmount: 0},
        {assetName: "background", propertyName: "color_4", propertyAmount: 0},
        {assetName: "background", propertyName: "color_5", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_1", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_2", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_3", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_4", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_5", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_1", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_2", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_3", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_4", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_5", propertyAmount: 0},
    
        {assetName: "optics", propertyName: "iron sights", propertyAmount: 0},
        {assetName: "optics", propertyName: "red dot", propertyAmount: 0},
        {assetName: "optics", propertyName: "4x scope", propertyAmount: 0},
        {assetName: "optics", propertyName: "thermal", propertyAmount: 0},
        {assetName: "optics", propertyName: "8x scope", propertyAmount: 0},
        {assetName: "optics", propertyName: "acog", propertyAmount: 0},
        {assetName: "optics", propertyName: "16x scope", propertyAmount: 0},
        {assetName: "optics", propertyName: "night vision", propertyAmount: 0},
    
        {assetName: "finish", propertyName: "all black", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_1 (camo 1)", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_2 (camo 2)", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_3 (camo 3)", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_4", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_5", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_6", propertyAmount: 0},
        {assetName: "finish", propertyName: "cardano", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_7", propertyAmount: 0},
        {assetName: "finish", propertyName: "urban", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_8", propertyAmount: 0},
        {assetName: "finish", propertyName: "dust", propertyAmount: 0},
        {assetName: "finish", propertyName: "black & gold", propertyAmount: 0},
        {assetName: "finish", propertyName: "marijuana", propertyAmount: 0},
        {assetName: "finish", propertyName: "jungle", propertyAmount: 0},
        {assetName: "finish", propertyName: "ice", propertyAmount: 0},
        {assetName: "finish", propertyName: "burn", propertyAmount: 0},
        {assetName: "finish", propertyName: "ghillie wrap", propertyAmount: 0},
        {assetName: "finish", propertyName: "reggae", propertyAmount: 0},
        {assetName: "finish", propertyName: "solid white", propertyAmount: 0},
        {assetName: "finish", propertyName: "green money bill", propertyAmount: 0},
        {assetName: "finish", propertyName: "psychedelic", propertyAmount: 0},
        {assetName: "finish", propertyName: "chrome", propertyAmount: 0},
        {assetName: "finish", propertyName: "gold", propertyAmount: 0},
    
        {assetName: "magazine", propertyName: "standard", propertyAmount: 0},
        {assetName: "magazine", propertyName: "extended", propertyAmount: 0},
        {assetName: "magazine", propertyName: "drum", propertyAmount: 0},
    
        {assetName: "stock", propertyName: "factory", propertyAmount: 0},
        {assetName: "stock", propertyName: "skeleton", propertyAmount: 0},
        {assetName: "stock", propertyName: "tactical_2", propertyAmount: 0},
        {assetName: "stock", propertyName: "tactical_3", propertyAmount: 0},
    
        {assetName: "muzzle", propertyName: "break", propertyAmount: 0},
        {assetName: "muzzle", propertyName: "silence", propertyAmount: 0},
        {assetName: "muzzle", propertyName: "flash", propertyAmount: 0},
        {assetName: "muzzle", propertyName: "compensator", propertyAmount: 0},
    
        {assetName: "attachment_1", propertyName: "none", propertyAmount: 0},
        {assetName: "attachment_1", propertyName: "laser", propertyAmount: 0},
        {assetName: "attachment_1", propertyName: "flashlight", propertyAmount: 0},
    
        {assetName: "attachment_2", propertyName: "none", propertyAmount: 0},
        {assetName: "attachment_2", propertyName: "bayonette", propertyAmount: 0},
        {assetName: "attachment_2", propertyName: "underbarrel shotgun", propertyAmount: 0},
        {assetName: "attachment_2", propertyName: "grenade launcher", propertyAmount: 0},
    
        {assetName: "attachment_3", propertyName: "none", propertyAmount: 0},
        {assetName: "attachment_3", propertyName: "vertical grip", propertyAmount: 0},
        {assetName: "attachment_3", propertyName: "foregrip", propertyAmount: 0},
    
        {assetName: "bonus", propertyName: "none", propertyAmount: 0},
        {assetName: "bonus", propertyName: "flashlight", propertyAmount: 0},
        {assetName: "bonus", propertyName: "ammo can", propertyAmount: 0},
        {assetName: "bonus", propertyName: "knife", propertyAmount: 0},
        {assetName: "bonus", propertyName: "radio", propertyAmount: 0},
        {assetName: "bonus", propertyName: "backpack", propertyAmount: 0},
        {assetName: "bonus", propertyName: "binoculars", propertyAmount: 0},
        {assetName: "bonus", propertyName: "med kit", propertyAmount: 0},
        {assetName: "bonus", propertyName: "flare", propertyAmount: 0},
        {assetName: "bonus", propertyName: "multi tool", propertyAmount: 0},
        {assetName: "bonus", propertyName: "pills", propertyAmount: 0},
        {assetName: "bonus", propertyName: "rocket launcher", propertyAmount: 0},
        {assetName: "bonus", propertyName: "money bag", propertyAmount: 0},
        {assetName: "bonus", propertyName: "atv", propertyAmount: 0},
        {assetName: "bonus", propertyName: "truck", propertyAmount: 0},
    ];

    return aug;
}

// ----------------------------------------------------------------------------

// 2,736
exports.getGALILData = () => {
    let galil = [
        {assetName: "background", propertyName: "color_1", propertyAmount: 166},
        {assetName: "background", propertyName: "color_2", propertyAmount: 225},
        {assetName: "background", propertyName: "color_3", propertyAmount: 294},
        {assetName: "background", propertyName: "color_4", propertyAmount: 314},
        {assetName: "background", propertyName: "color_5", propertyAmount: 369},
        {assetName: "background", propertyName: "landscape_1", propertyAmount: 241},
        {assetName: "background", propertyName: "landscape_2", propertyAmount: 397},
        {assetName: "background", propertyName: "landscape_3", propertyAmount: 137},
        {assetName: "background", propertyName: "landscape_4", propertyAmount: 291},
        {assetName: "background", propertyName: "landscape_5", propertyAmount: 28},
        {assetName: "background", propertyName: "unique_1", propertyAmount: 7},
        {assetName: "background", propertyName: "unique_2", propertyAmount: 30},
        {assetName: "background", propertyName: "unique_3", propertyAmount: 48},
        {assetName: "background", propertyName: "unique_4", propertyAmount: 73},
        {assetName: "background", propertyName: "unique_5", propertyAmount: 116},
    
        {assetName: "optics", propertyName: "iron sights", propertyAmount: 1685},
        {assetName: "optics", propertyName: "red dot", propertyAmount: 404},
        {assetName: "optics", propertyName: "4x scope", propertyAmount: 365},
        {assetName: "optics", propertyName: "thermal", propertyAmount: 28},
        {assetName: "optics", propertyName: "8x scope", propertyAmount: 96},
        {assetName: "optics", propertyName: "acog", propertyAmount: 115},
        {assetName: "optics", propertyName: "16x scope", propertyAmount: 33},
        {assetName: "optics", propertyName: "night vision", propertyAmount: 10},
    
        {assetName: "finish", propertyName: "all black", propertyAmount: 268},
        {assetName: "finish", propertyName: "skin_1 (camo 1)", propertyAmount: 173},
        {assetName: "finish", propertyName: "skin_2 (camo 2)", propertyAmount: 167},
        {assetName: "finish", propertyName: "skin_3 (camo 3)", propertyAmount: 192},
        {assetName: "finish", propertyName: "skin_4", propertyAmount: 162},
        {assetName: "finish", propertyName: "skin_5", propertyAmount: 159},
        {assetName: "finish", propertyName: "skin_6", propertyAmount: 144},
        {assetName: "finish", propertyName: "cardano", propertyAmount: 142},
        {assetName: "finish", propertyName: "skin_7", propertyAmount: 137},
        {assetName: "finish", propertyName: "urban", propertyAmount: 131},
        {assetName: "finish", propertyName: "skin_8", propertyAmount: 125},
        {assetName: "finish", propertyName: "dust", propertyAmount: 115},
        {assetName: "finish", propertyName: "black & gold", propertyAmount: 82},
        {assetName: "finish", propertyName: "marijuana", propertyAmount: 108},
        {assetName: "finish", propertyName: "jungle", propertyAmount: 101},
        {assetName: "finish", propertyName: "ice", propertyAmount: 94},
        {assetName: "finish", propertyName: "burn", propertyAmount: 87},
        {assetName: "finish", propertyName: "ghillie wrap", propertyAmount: 78},
        {assetName: "finish", propertyName: "reggae", propertyAmount: 71},
        {assetName: "finish", propertyName: "solid white", propertyAmount: 66},
        {assetName: "finish", propertyName: "green money bill", propertyAmount: 58},
        {assetName: "finish", propertyName: "psychedelic", propertyAmount: 49},
        {assetName: "finish", propertyName: "chrome", propertyAmount: 22},
        {assetName: "finish", propertyName: "gold", propertyAmount: 5},
    
        {assetName: "magazine", propertyName: "standard", propertyAmount: 2316},
        {assetName: "magazine", propertyName: "extended", propertyAmount: 277},
        {assetName: "magazine", propertyName: "drum", propertyAmount: 143},
    
        {assetName: "stock", propertyName: "factory", propertyAmount: 1658},
        {assetName: "stock", propertyName: "skeleton", propertyAmount: 335},
        {assetName: "stock", propertyName: "tactical_2", propertyAmount: 566},
        {assetName: "stock", propertyName: "tactical_3", propertyAmount: 177},
    
        {assetName: "muzzle", propertyName: "break", propertyAmount: 1355},
        {assetName: "muzzle", propertyName: "silence", propertyAmount: 110},
        {assetName: "muzzle", propertyName: "flash", propertyAmount: 965},
        {assetName: "muzzle", propertyName: "compensator", propertyAmount: 306},
    
        {assetName: "attachment_1", propertyName: "none", propertyAmount: 1438},
        {assetName: "attachment_1", propertyName: "laser", propertyAmount: 111},
        {assetName: "attachment_1", propertyName: "flashlight", propertyAmount: 1187},
    
        {assetName: "attachment_2", propertyName: "none", propertyAmount: 2393},
        {assetName: "attachment_2", propertyName: "bayonette", propertyAmount: 84},
        {assetName: "attachment_2", propertyName: "underbarrel shotgun", propertyAmount: 93},
        {assetName: "attachment_2", propertyName: "grenade launcher", propertyAmount: 166},
    
        {assetName: "attachment_3", propertyName: "none", propertyAmount: 2259},
        {assetName: "attachment_3", propertyName: "vertical grip", propertyAmount: 205},
        {assetName: "attachment_3", propertyName: "foregrip", propertyAmount: 272},
    
        {assetName: "bonus", propertyName: "none", propertyAmount: 1401},
        {assetName: "bonus", propertyName: "flashlight", propertyAmount: 203},
        {assetName: "bonus", propertyName: "ammo can", propertyAmount: 200},
        {assetName: "bonus", propertyName: "knife", propertyAmount: 180},
        {assetName: "bonus", propertyName: "radio", propertyAmount: 131},
        {assetName: "bonus", propertyName: "backpack", propertyAmount: 123},
        {assetName: "bonus", propertyName: "binoculars", propertyAmount: 110},
        {assetName: "bonus", propertyName: "med kit", propertyAmount: 108},
        {assetName: "bonus", propertyName: "flare", propertyAmount: 84},
        {assetName: "bonus", propertyName: "multi tool", propertyAmount: 74},
        {assetName: "bonus", propertyName: "pills", propertyAmount: 73},
        {assetName: "bonus", propertyName: "rocket launcher", propertyAmount: 21},
        {assetName: "bonus", propertyName: "money bag", propertyAmount: 19},
        {assetName: "bonus", propertyName: "atv", propertyAmount: 8},
        {assetName: "bonus", propertyName: "truck", propertyAmount: 1},
    ];

    return galil;
}

// ----------------------------------------------------------------------------

// 3,281
exports.getM4A1Data = () => {
    let m4a1 = [
        {assetName: "background", propertyName: "color_1", propertyAmount: 0},
        {assetName: "background", propertyName: "color_2", propertyAmount: 0},
        {assetName: "background", propertyName: "color_3", propertyAmount: 0},
        {assetName: "background", propertyName: "color_4", propertyAmount: 0},
        {assetName: "background", propertyName: "color_5", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_1", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_2", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_3", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_4", propertyAmount: 0},
        {assetName: "background", propertyName: "landscape_5", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_1", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_2", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_3", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_4", propertyAmount: 0},
        {assetName: "background", propertyName: "unique_5", propertyAmount: 0},
    
        {assetName: "optics", propertyName: "iron sights", propertyAmount: 0},
        {assetName: "optics", propertyName: "red dot", propertyAmount: 0},
        {assetName: "optics", propertyName: "4x scope", propertyAmount: 0},
        {assetName: "optics", propertyName: "thermal", propertyAmount: 0},
        {assetName: "optics", propertyName: "8x scope", propertyAmount: 0},
        {assetName: "optics", propertyName: "acog", propertyAmount: 0},
        {assetName: "optics", propertyName: "16x scope", propertyAmount: 0},
        {assetName: "optics", propertyName: "night vision", propertyAmount: 0},
    
        {assetName: "finish", propertyName: "all black", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_1 (camo 1)", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_2 (camo 2)", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_3 (camo 3)", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_4", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_5", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_6", propertyAmount: 0},
        {assetName: "finish", propertyName: "cardano", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_7", propertyAmount: 0},
        {assetName: "finish", propertyName: "urban", propertyAmount: 0},
        {assetName: "finish", propertyName: "skin_8", propertyAmount: 0},
        {assetName: "finish", propertyName: "dust", propertyAmount: 0},
        {assetName: "finish", propertyName: "black & gold", propertyAmount: 0},
        {assetName: "finish", propertyName: "marijuana", propertyAmount: 0},
        {assetName: "finish", propertyName: "jungle", propertyAmount: 0},
        {assetName: "finish", propertyName: "ice", propertyAmount: 0},
        {assetName: "finish", propertyName: "burn", propertyAmount: 0},
        {assetName: "finish", propertyName: "ghillie wrap", propertyAmount: 0},
        {assetName: "finish", propertyName: "reggae", propertyAmount: 0},
        {assetName: "finish", propertyName: "solid white", propertyAmount: 0},
        {assetName: "finish", propertyName: "green money bill", propertyAmount: 0},
        {assetName: "finish", propertyName: "psychedelic", propertyAmount: 0},
        {assetName: "finish", propertyName: "chrome", propertyAmount: 0},
        {assetName: "finish", propertyName: "gold", propertyAmount: 0},
    
        {assetName: "magazine", propertyName: "standard", propertyAmount: 0},
        {assetName: "magazine", propertyName: "extended", propertyAmount: 0},
        {assetName: "magazine", propertyName: "drum", propertyAmount: 0},
    
        {assetName: "stock", propertyName: "factory", propertyAmount: 0},
        {assetName: "stock", propertyName: "skeleton", propertyAmount: 0},
        {assetName: "stock", propertyName: "tactical_2", propertyAmount: 0},
        {assetName: "stock", propertyName: "tactical_3", propertyAmount: 0},
    
        {assetName: "muzzle", propertyName: "break", propertyAmount: 0},
        {assetName: "muzzle", propertyName: "silence", propertyAmount: 0},
        {assetName: "muzzle", propertyName: "flash", propertyAmount: 0},
        {assetName: "muzzle", propertyName: "compensator", propertyAmount: 0},
    
        {assetName: "attachment_1", propertyName: "none", propertyAmount: 0},
        {assetName: "attachment_1", propertyName: "laser", propertyAmount: 0},
        {assetName: "attachment_1", propertyName: "flashlight", propertyAmount: 0},
    
        {assetName: "attachment_2", propertyName: "none", propertyAmount: 0},
        {assetName: "attachment_2", propertyName: "bayonette", propertyAmount: 0},
        {assetName: "attachment_2", propertyName: "underbarrel shotgun", propertyAmount: 0},
        {assetName: "attachment_2", propertyName: "grenade launcher", propertyAmount: 0},
    
        {assetName: "attachment_3", propertyName: "none", propertyAmount: 0},
        {assetName: "attachment_3", propertyName: "vertical grip", propertyAmount: 0},
        {assetName: "attachment_3", propertyName: "foregrip", propertyAmount: 0},
    
        {assetName: "bonus", propertyName: "none", propertyAmount: 0},
        {assetName: "bonus", propertyName: "flashlight", propertyAmount: 0},
        {assetName: "bonus", propertyName: "ammo can", propertyAmount: 0},
        {assetName: "bonus", propertyName: "knife", propertyAmount: 0},
        {assetName: "bonus", propertyName: "radio", propertyAmount: 0},
        {assetName: "bonus", propertyName: "backpack", propertyAmount: 0},
        {assetName: "bonus", propertyName: "binoculars", propertyAmount: 0},
        {assetName: "bonus", propertyName: "med kit", propertyAmount: 0},
        {assetName: "bonus", propertyName: "flare", propertyAmount: 0},
        {assetName: "bonus", propertyName: "multi tool", propertyAmount: 0},
        {assetName: "bonus", propertyName: "pills", propertyAmount: 0},
        {assetName: "bonus", propertyName: "rocket launcher", propertyAmount: 0},
        {assetName: "bonus", propertyName: "money bag", propertyAmount: 0},
        {assetName: "bonus", propertyName: "atv", propertyAmount: 0},
        {assetName: "bonus", propertyName: "truck", propertyAmount: 0},
    ];

    return m4a1;
}